# Generated by Django 5.0.4 on 2026-07-07 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userprofile_telefono'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
