# Generated by Django 5.2.8 on 2026-03-26 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Titular',
            fields=[
                ('cedula', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Cédula')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=10)),
                ('estado_civil', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono_principal', models.CharField(max_length=20)),
                ('telefono_secundario', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.TextField()),
                ('fecha_ingreso', models.DateField()),
                ('fecha_egreso', models.DateField(blank=True, null=True)),
                ('dependencia', models.CharField(max_length=100)),
                ('tipo_empleado', models.CharField(max_length=50)),
                ('estado_laboral', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=100)),
                ('status_laboral', models.CharField(max_length=50)),
                ('cuenta_nomina', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_nomina', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CargaFamiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(blank=True, max_length=20, null=True, verbose_name='Cédula (si aplica)')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=10)),
                ('estado_civil', models.CharField(max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('parentesco', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('certificado_medico', models.BooleanField(default=False)),
                ('lugar_registro', models.CharField(blank=True, max_length=100, null=True)),
                ('titular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargas', to='administrador.titular')),
            ],
        ),
    ]
