# Generated by Django 5.2.8 on 2026-03-26 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargafamiliar',
            options={'verbose_name': 'Carga Familiar', 'verbose_name_plural': 'Cargas Familiares'},
        ),
        migrations.AlterModelOptions(
            name='titular',
            options={'verbose_name': 'Titular', 'verbose_name_plural': 'Titulares'},
        ),
        migrations.AlterField(
            model_name='cargafamiliar',
            name='apellidos',
            field=models.CharField(max_length=100, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='cargafamiliar',
            name='certificado_medico',
            field=models.BooleanField(default=False, verbose_name='Certificado Médico'),
        ),
        migrations.AlterField(
            model_name='cargafamiliar',
            name='estado_civil',
            field=models.CharField(max_length=20, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='cargafamiliar',
            name='fecha_nacimiento',
            field=models.DateField(verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='cargafamiliar',
            name='lugar_registro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lugar de Registro'),
        ),
        migrations.AlterField(
            model_name='cargafamiliar',
            name='nombres',
            field=models.CharField(max_length=100, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='cargafamiliar',
            name='parentesco',
            field=models.CharField(max_length=50, verbose_name='Parentesco'),
        ),
        migrations.AlterField(
            model_name='cargafamiliar',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=10, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='cargafamiliar',
            name='status',
            field=models.CharField(max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='cargafamiliar',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='cargafamiliar',
            name='titular',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargas', to='administrador.titular', verbose_name='Titular'),
        ),
        migrations.AlterField(
            model_name='titular',
            name='apellidos',
            field=models.CharField(max_length=100, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='titular',
            name='cargo',
            field=models.CharField(max_length=100, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='titular',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='titular',
            name='cuenta_nomina',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cuenta Nómina'),
        ),
        migrations.AlterField(
            model_name='titular',
            name='dependencia',
            field=models.CharField(max_length=100, verbose_name='Dependencia'),
        ),
        migrations.AlterField(
            model_name='titular',
            name='direccion',
            field=models.TextField(verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='titular',
            name='estado_civil',
            field=models.CharField(max_length=20, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='titular',
            name='estado_laboral',
            field=models.CharField(max_length=50, verbose_name='Estado Laboral'),
        ),
        migrations.AlterField(
            model_name='titular',
            name='fecha_egreso',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Egreso'),
        ),
        migrations.AlterField(
            model_name='titular',
            name='fecha_ingreso',
            field=models.DateField(verbose_name='Fecha de Ingreso'),
        ),
        migrations.AlterField(
            model_name='titular',
            name='fecha_nacimiento',
            field=models.DateField(verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='titular',
            name='nacionalidad',
            field=models.CharField(max_length=50, verbose_name='Nacionalidad'),
        ),
        migrations.AlterField(
            model_name='titular',
            name='nombres',
            field=models.CharField(max_length=100, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='titular',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=10, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='titular',
            name='status_laboral',
            field=models.CharField(max_length=50, verbose_name='Status Laboral'),
        ),
        migrations.AlterField(
            model_name='titular',
            name='telefono_principal',
            field=models.CharField(max_length=20, verbose_name='Teléfono Principal'),
        ),
        migrations.AlterField(
            model_name='titular',
            name='telefono_secundario',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono Secundario'),
        ),
        migrations.AlterField(
            model_name='titular',
            name='tipo_empleado',
            field=models.CharField(max_length=50, verbose_name='Tipo de Empleado'),
        ),
        migrations.AlterField(
            model_name='titular',
            name='tipo_nomina',
            field=models.CharField(max_length=50, verbose_name='Tipo de Nómina'),
        ),
    ]
